# -*- coding: utf-8 -*-

##########################http相关##################################
# 成功
RET_SUCESS = 0
# 非法客户端
RET_CODE_WRONG_CLIENT = 100300
# 客户端无授权
RET_CODE_NO_LICENCE = 100301

##########################应用内部####################################
# 成功
APP_RET_CODE_SUCESS = 0
# 找不到
APP_RET_CODE_NO_FOUND = 1
# 主动退出
APP_RET_CODE_ZHU_DONG_EXIT = -1 
# APP卡住
APP_RET_CODE_APP_KA_ZHU = -2 
# 授权到期 
APP_RET_CODE_LIC_OUTDATE = -3 
# 网络异常 
APP_RET_CODE_NET_ERROR = -4
# 应用退出
APP_RET_CODE_APP_EXIT = -5 
# 服务器端异常
APP_RET_CODE_SERVER_ERRE = -6 
# 非安全的问答
APP_RET_CODE_UN_SAFE_QUESTION = -7 
# 知识库里找不到答案的问题
APP_RET_CODE_NO_ANSWER_IN_KNOWLEDAGE = -8
# 此好友不可添加
APP_RET_CODE_CANNOT_ADD = -9
# 没有可执行的任务
APP_RET_CODE_NO_CAN_EXE_TASK = -10
# 未初始化
APP_RET_CODE_NO_INITED = -11 
# 入参不满足
APP_RET_CODE_UNVALID_PARAM = -12 
# 未准备好
APP_RET_CODE_NO_READY = -13 
# OCR出错
APP_RET_CODE_OCR_ERROR = -14 
# 已经完成 
APP_RET_CODE_HAS_FINISH = -15
# 大模型API调用量耗尽
APP_RET_CODE_LLM_API_EXCEEDED = -16
# 时间还没到
APP_RET_CODE_TIME_NOT_READY = -17
# 此好友没找到
APP_RET_CODE_FRIEND_NO_FOUND = -18
# 不符合格式
APP_RET_CODE_FORMAT_ERROR = -19
# 还没完成
APP_RET_CODE_NO_FINISH = -20
# 此群已解散
APP_RET_CODE_GROUP_HAS_RELEASE = -21
# 手机还没处于连接状态
APP_RET_CODE_PHONE_NO_CONNECT = -22
# 手机还没点亮
APP_RET_CODE_PHONE_NO_LIGHT = -23
# 手机还没解锁
APP_RET_CODE_PHONE_NO_UNLOCK = -24
# 微信安装
APP_RET_CODE_WECHAT_NO_INSTALL = -25
# 微信还没运行
APP_RET_CODE_WECHAT_NO_RUNNING = -26
# 微信没在顶层
APP_RET_CODE_WECHAT_NO_TOP = -27
# 微信窗口没有在屏幕内
APP_RET_CODE_WECHAT_NO_IN_SCREEN = -28
# 微信不可见（被全部挡住）
APP_RET_CODE_WECHAT_NO_VISIBLE = -29
# 微信被部分挡住
APP_RET_CODE_WECHAT_NO_VISIBLE_PART = -30
# 微信没在屏幕的正中间
APP_RET_CODE_WECHAT_NO_IN_CENTER = -31
# 微信没在主窗体的外面
APP_RET_CODE_WECHAT_NO_IN_OUT= -32

# 弹出框异常(未知窗口)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_UNKNOW = -115
# 弹出框异常(权限申请页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_AUTHORITY = -116
# 弹出框异常(二维码登录页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_QRCODE_LOGION = -117
# 弹出框异常(进入微信页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_ENTER_WECHAT = -118
# 弹出框异常(需在手机上完成登录要面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_NEED_PHONE_LOGION = -119
# 弹出框异常(登录注册页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_LOGION_REG = -120
# 弹出框异常(使用设备类型设置页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_USE_DEVICE_TYPE = -121
# 弹出框异常(使用设备类型设置页面2)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_USE_DEVICE_TYPE2 = -122
# 弹出框异常(使用设备类型设置仅平板页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_USE_DEVICE_TYPE_ONLY_PAD = -123
# 弹出框异常(雷电主页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_LEI_DIAN_MAIN = -124
# 弹出框异常(等待手机上确认页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_WAIT_CONFIRM = -125
# 弹出框异常(正在载入数据页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_LODING_DATA = -126
# 弹出框异常(微信可设置字体大小页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_SETTING_FONT = -127
# 弹出框异常(本次登录已失效页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_LOGIN_LOSS = -128
# 弹出框异常(切换验证方式页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_CHANGE_LOGIN_METHOD = -129
# 弹出框异常(切换验证方式(不期待的)页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_CHANGE_LOGIN_METHOD_UNEXPECT = -130
# 弹出框异常(切换验证方式仅平板登录页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_CHANGE_LOGIN_METHOD_PAD = -131
# 弹出框异常(允许微信录音吗页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_CAN_LU_YIN = -132
# 弹出框异常(当前账号已经在其他设备登录页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_HAS_LOGIN_IN_OTHER = -133
# 弹出框异常(登录过期请重新登录页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_RE_LOGIN = -134
# 弹出框异常(为了你的安全请重新登录页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_SAFE_RE_LOGIN = -135
# 弹出框异常(密码登录页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_SECRET_LOGIN = -136
# 弹出框异常(当前账号已经在其他设备登录页面2)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_HAS_LOGIN_IN_OTHER_2 = -137
# 弹出框异常(登录出现错误,请你重新登录页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_ERROR_LOGIN_RE = -138
# 弹出框异常(允许微信拍摄照片和录制视频页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_CAN_IMAGE = -139
# 弹出框异常(微信屡次停止运行)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_STOP_RUN = -140
# 弹出框异常(微信没有响应)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_NO_RESPONSE = -141
# 弹出框异常(初始使用朋友圈发送文本提醒页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_ERROR_SEND_CIRCLE_TEXT_REMIND = -142
# 弹出框异常(微信申请访问照片权限)
APP_RET_CODE_WEI_XIN_APPLY_VISIT_AMBLE = -143
# 弹出框异常(麦克见权限未开启)
APP_RET_CODE_MIC_AUTHORITY_NO_OPEN = -144
# 弹出框异常(你已退出微信)
APP_RET_CODE_YOU_HAS_LOGOUT_WECHAT = -145
# 弹出框异常(系统界面没有响应)
APP_RET_CODE_SYSTEM_UI_NO_RESPONSE = -146
# 弹出框异常(权限申请保持后台页面)
APP_RET_CODE_HAS_MESSAGBOX_EXCEPTION_AUTHORITY_KEEY_BACK = -147
# 弹出框异常(进入非期待的聊天页面)
APP_RET_CODE_UNEXPECT_CHAT_PAGE = -148
# 弹出框异常(账号在其他设备上登录)
APP_RET_CODE_HAS_LOGIN_IN_OTHER = -149
# 弹出框异常(提示：由于对方的隐私设置)
APP_RET_CODE_MSG_BECAUSE_PRIVACY = -150
# 弹出框异常(小程序入口提示)
APP_RET_CODE_MSG_SMALL_PROGRAM = -151
# 弹出框异常(保留此次编辑)
APP_RET_CODE_MSG_KEEP_EDIT = -152

# 已经是在期待页面
APP_RET_CODE_HAS_IN_EXPECT_PAGE = -997

# 未知错误
APP_RET_CODE_UNKNOW = -999